config/routes.rb
Myapp::Application.routes.draw do

  resources :feature_assignments
  resources :features
  get 'landing/set_role'

  mount ActionCable.server => '/cable'
  resources :ticket_approvals do
    member do
      post 'approvals', to: "ticket_approvals#approve"
      post 'reject', to: "ticket_approvals#reject"
      # post 'ticket_approvals/reject'
      # post 'ticket_approvals/approve'
    end
  end  
  resources :ticket_problems
  resources :message_templates
  resources :assetlisensis
  resources :assetssystems
  resources :changes do
    member do 
      delete "delete_file/:attachment_id", to: 'changes#delete_file'  
    end
  end
  resources :process_tickets do
    member do
      get "processTechnician", to: "process_tickets#processTechnician"
      get "processClosingAdmin", to: "process_tickets#processClosingAdmin"
      get "confirmWaiting", to: "process_tickets#confirmWaiting"
      get "createProblem", to: "process_tickets#createProblem"
      get "createPriority", to: "process_tickets#createPriority"
    end
  end
  post 'process_tickets/createFollowupTechnician'
  post 'process_tickets/followup'
  post 'process_tickets/createClosing'
  post 'process_tickets/createSatisfaction'
  post 'process_tickets/createSatisfactionEskalasi'
  post 'users/updateProfileForSelfService'
  resources :loss_events
  resources :positions
  # post '/update_session', to: 'helper_json#update_session_feature'
  post '/update_session_feature', to: 'helper_json#update_session_feature'


  resources :helper_json do
    collection do

      get "/getTemplateTiket", to: "helper_json#getTemplateTiket"
    end
    member do
      
      get 'destroy_chat', to: 'helper_json#destroy_chat', as: 'ticket_destroy_chat'

      get "getTemplatesByJenisLayanan", to: "helper_json#getTemplatesByJenisLayanan"
      get "getTemplatesBySubKategori", to: "helper_json#getTemplatesBySubKategori"

      get "getTemplatesByKategori/:kategori_id", to: "helper_json#getTemplatesByKategori"
      get "getTemplatesInAdminByKategori/:kategori_id", to: "helper_json#getTemplatesInAdminByKategori"
      

      get "getTemplates/:jenis_layanan", to: "helper_json#getTemplates"

      get "getSubKategori", to: "helper_json#getSubKategori"
      get "getSubKategori2", to: "helper_json#getSubKategori2"
      get "getPriority", to: "helper_json#getPriority"
      get "getStatusTeknisi", to: "helper_json#getStatusTeknisi"
      get "switchRole", to: "helper_json#switchRole"
      get "getTeknisi", to: "helper_json#getTeknisi"
      get "getPic", to: "helper_json#getPic"
      get "getStatus", to: "helper_json#getPic"
      get "getMerkPerangkat", to: "helper_json#getMerkPerangkat"
      get "getTipePerangkat", to: "helper_json#getTipePerangkat"
      get "getSubLayanan", to: "helper_json#getSubLayanan"
      get "getPerintilan", to: "helper_json#getPerintilan"
      get "getLayanan", to: "helper_json#getLayanan"
    end
  end
  resources :tickets do
    # get "notification", to: "tickets#read_ticket"


    collection do
      get 'cetak_pdf', to: "tickets#cetak_pdf"
      get 'cetak_excel', to: "tickets#cetak_excel"
      get 'detail_notif', to: "tickets#detail_notif"
      
    end
    member do
      get "superadminEdit", to: "tickets#superadminEdit"
      get "follow_up", to: "tickets#follow_up"
      get "answer", to: "tickets#answer"
      get "notification", to: "tickets#read_ticket"
      get 'chat_notif/:ticket_history', to: 'tickets#read_ticket_chat', as: 'chat_notif_ticket'      
      get "read_all_notifications/:ticket_history", to: "tickets#read_all_notifications", as: "read_all_notifications"
    end

  end
  resources :collection_assets
  resources :categories do
    member do 
      delete "delete_file/:attachment_id", to: 'categories#delete_file'   
    end
  end
  resources :service_types
  resources :assetsdigitals do
    collection do 
      post :import
    end
  end

  resources :assetsusers do
    member do 
      delete "delete_file/:attachment_id", to: 'assetsusers#delete_file'   
    end
    collection do
      post :import
        get 'cetak_pdf', to: "assetsusers#cetak_pdf"
        get 'cetak_excel', to: "assetsusers#cetak_excel"
    end
  end
  resources :assetssits
  # You can have the root of your site routed with "root"
  root to: 'dashboards#home'


  devise_for :users, path: '', path_names: { sign_in: 'login_page', sign_out: 'logout'}, controllers:{
    sessions: 'users/sessions'
  }
  resources :areas
  resources :roles
  resources :users

  # get ":category_id/", to: "dashboards#home"


  #sub_category
resources :dashboards do
  get "/insiden/", to: "dashboards#insiden_layanan"
  get "/request/", to: "dashboards#request_layanan"

end


  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/home"

  get "layoutsoptions/index"

  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/peity"
  get "graphs/sparkline"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/jqgrid"

  get "gallery/basic_gallery"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"


  mount RailsPerformance::Engine, at: 'rails/performance'


  # match '*path', via: :all, to: 'pages#not_found_error', constraints: lambda { |req|
  #   req.path.exclude? 'rails/active_storage'
  # }
  # get '/500', to: 'errors#internal_server_error'
  # get '/404', to: 'errors#not_found'
  # get '/422', to: 'errors#unprocessable_entity'
  
  # match '/500', via: :all, to: 'pages#internal_server_error'
  # match '/page_cannot_be_found', via: :all, to: 'pages#page_cannot_be_found'

end

app/models/loss_event.rb
class LossEvent  < ActiveRecord::Base
end

app/controllers/loss_events_controller.rb
class LossEventsController < ApplicationController
  before_action :set_loss_event, only: %i[ show edit update destroy ]

  # GET /loss_events or /loss_events.json
  def index
    @loss_events = LossEvent.all
  end

  # GET /loss_events/1 or /loss_events/1.json
  def show
  end

  # GET /loss_events/new
  def new
    @loss_event = LossEvent.new
    @teknisi = RoleAssignment.includes(:user).where(role_id: 3).map{|value| value.user.name} 
  end

  # GET /loss_events/1/edit
  def edit
    @teknisi = RoleAssignment.includes(:user).where(role_id: 3).map{|value| value.user.name} 
  end

  # POST /loss_events or /loss_events.json
  def create
    @loss_event = LossEvent.new(loss_event_params)

    respond_to do |format|
      if @loss_event.save
        format.html { redirect_to loss_event_url(@loss_event), notice: "Loss event was successfully created." }
        format.json { render :show, status: :created, location: @loss_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loss_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loss_events/1 or /loss_events/1.json
  def update
    respond_to do |format|
      if @loss_event.update(loss_event_params)
        format.html { redirect_to loss_event_url(@loss_event), notice: "Loss event was successfully updated." }
        format.json { render :show, status: :ok, location: @loss_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loss_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loss_events/1 or /loss_events/1.json
  def destroy
    @loss_event.destroy

    respond_to do |format|
      format.html { redirect_to loss_events_url, notice: "Loss event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loss_event
      @loss_event = LossEvent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loss_event_params
      params.require(:loss_event).permit(:nama, :tanggal, :tempat, :status, :pic, :deskripsi_kejadian, :kategori)
    end
end

app/helpers/loss_events_helper.rb
module LossEventsHelper
end

app/views/loss_events/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Form loss_event</div>
  <div class="panel-body">
<%= form_for(@loss_event, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @loss_event.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@loss_event.errors.count, "error") %> prohibited this loss_event from being saved:</h4>

      <ul>
      <% @loss_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nama, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nama, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tanggal, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_field :tanggal, class: "form-control", data: { date_format: 'yyyy-mm-dd' } %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tempat, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tempat, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :status, options_for_select(['Open', 'Closed', 'On Processing']), {}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pic, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :pic, @teknisi, :to_s, :to_s, { include_blank: true }, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :kategori, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :kategori, options_for_select(['Server', 'Jaringan', 'Aplikasi']), {}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deskripsi_kejadian, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :deskripsi_kejadian, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
  </div>
</div>

app/views/loss_events/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form loss_event</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= loss_events_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to loss_events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
    <% end %>
    <%= link_to @loss_event, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
    <% end %>
    <h1>Editing loss_event</h1>
  </div>

  <%= render 'form' %>
</div>

app/views/loss_events/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form loss_event</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= loss_events_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to new_loss_event_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Loss event
    <% end %>
    <!--    <h1>Listing </h1>-->
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover dataTables-example">
      <thead>
      <tr>
        <th>No</th>
                  <th>Nama</th>
                  <th>Tanggal</th>
                  <th>Tempat</th>
                  <th>Status</th>
                  <th>Pic</th>
                  <th>Deskripsi kejadian</th>
                  <th>Kategori</th>
                  <th>Aksi</th>
      </tr>
      </thead>

      <tbody>
      <% @loss_events.each_with_index do |loss_event, index| %>
      <tr>
        <td><%= index+1 %></td>
                  <td><%= loss_event.nama %></td>
                  <td><%= loss_event.tanggal %></td>
                  <td><%= loss_event.tempat %></td>
                  <td><%= loss_event.status %></td>
                  <td><%= loss_event.pic %></td>
                  <td><%= loss_event.deskripsi_kejadian %></td>
                  <td><%= loss_event.kategori %></td>
                <td>
                <%= link_to 'Show', loss_event %>
                    <%= link_to 'Edit', edit_loss_event_path(loss_event) %>
                    <%= link_to 'Destroy', loss_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/loss_events/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form loss_event</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= loss_events_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <%= render 'form' %>
</div>

app/views/loss_events/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form loss_event</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= loss_events_url %>">List</a>
      </li>
      <li class="active">
        <strong>Detail</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to loss_events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
    <% end %>
    <%= link_to edit_loss_event_path(@loss_event), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
    <% end %>
<!--    <h1>Show </h1>-->
  </div>

  <dl class="dl-horizontal">
      <dt>Nama:</dt>
      <dd><%= @loss_event.nama %></dd>

      <dt>Tanggal:</dt>
      <dd><%= @loss_event.tanggal %></dd>

      <dt>Tempat:</dt>
      <dd><%= @loss_event.tempat %></dd>

      <dt>Status:</dt>
      <dd><%= @loss_event.status %></dd>

      <dt>Pic:</dt>
      <dd><%= @loss_event.pic %></dd>

      <dt>Deskripsi kejadian:</dt>
      <dd><%= @loss_event.deskripsi_kejadian %></dd>

      <dt>Kategori:</dt>
      <dd><%= @loss_event.kategori %></dd>

  </dl>
</div>