config/routes.rb
Myapp::Application.routes.draw do

  resources :feature_assignments
  resources :features
  get 'landing/set_role'

  mount ActionCable.server => '/cable'
  resources :ticket_approvals do
    member do
      post 'approvals', to: "ticket_approvals#approve"
      post 'reject', to: "ticket_approvals#reject"
      # post 'ticket_approvals/reject'
      # post 'ticket_approvals/approve'
    end
  end  
  resources :ticket_problems
  resources :message_templates
  resources :assetlisensis
  resources :assetssystems
  resources :changes do
    member do 
      delete "delete_file/:attachment_id", to: 'changes#delete_file'  
    end
  end
  resources :process_tickets do
    member do
      get "processTechnician", to: "process_tickets#processTechnician"
      get "processClosingAdmin", to: "process_tickets#processClosingAdmin"
      get "confirmWaiting", to: "process_tickets#confirmWaiting"
      get "createProblem", to: "process_tickets#createProblem"
      get "createPriority", to: "process_tickets#createPriority"
    end
  end
  post 'process_tickets/createFollowupTechnician'
  post 'process_tickets/followup'
  post 'process_tickets/createClosing'
  post 'process_tickets/createSatisfaction'
  post 'process_tickets/createSatisfactionEskalasi'
  post 'users/updateProfileForSelfService'
  resources :loss_events
  resources :positions
  # post '/update_session', to: 'helper_json#update_session_feature'
  post '/update_session_feature', to: 'helper_json#update_session_feature'


  resources :helper_json do
    collection do

      get "/getTemplateTiket", to: "helper_json#getTemplateTiket"
    end
    member do
      
      get 'destroy_chat', to: 'helper_json#destroy_chat', as: 'ticket_destroy_chat'

      get "getTemplatesByJenisLayanan", to: "helper_json#getTemplatesByJenisLayanan"
      get "getTemplatesBySubKategori", to: "helper_json#getTemplatesBySubKategori"

      get "getTemplatesByKategori/:kategori_id", to: "helper_json#getTemplatesByKategori"
      get "getTemplatesInAdminByKategori/:kategori_id", to: "helper_json#getTemplatesInAdminByKategori"
      

      get "getTemplates/:jenis_layanan", to: "helper_json#getTemplates"

      get "getSubKategori", to: "helper_json#getSubKategori"
      get "getSubKategori2", to: "helper_json#getSubKategori2"
      get "getPriority", to: "helper_json#getPriority"
      get "getStatusTeknisi", to: "helper_json#getStatusTeknisi"
      get "switchRole", to: "helper_json#switchRole"
      get "getTeknisi", to: "helper_json#getTeknisi"
      get "getPic", to: "helper_json#getPic"
      get "getStatus", to: "helper_json#getPic"
      get "getMerkPerangkat", to: "helper_json#getMerkPerangkat"
      get "getTipePerangkat", to: "helper_json#getTipePerangkat"
      get "getSubLayanan", to: "helper_json#getSubLayanan"
      get "getPerintilan", to: "helper_json#getPerintilan"
      get "getLayanan", to: "helper_json#getLayanan"
    end
  end
  resources :tickets do
    # get "notification", to: "tickets#read_ticket"


    collection do
      get 'cetak_pdf', to: "tickets#cetak_pdf"
      get 'cetak_excel', to: "tickets#cetak_excel"
      get 'detail_notif', to: "tickets#detail_notif"
      
    end
    member do
      get "superadminEdit", to: "tickets#superadminEdit"
      get "follow_up", to: "tickets#follow_up"
      get "answer", to: "tickets#answer"
      get "notification", to: "tickets#read_ticket"
      get 'chat_notif/:ticket_history', to: 'tickets#read_ticket_chat', as: 'chat_notif_ticket'      
      get "read_all_notifications/:ticket_history", to: "tickets#read_all_notifications", as: "read_all_notifications"
    end

  end
  resources :collection_assets
  resources :categories do
    member do 
      delete "delete_file/:attachment_id", to: 'categories#delete_file'   
    end
  end
  resources :service_types
  resources :assetsdigitals do
    collection do 
      post :import
    end
  end

  resources :assetsusers do
    member do 
      delete "delete_file/:attachment_id", to: 'assetsusers#delete_file'   
    end
    collection do
      post :import
        get 'cetak_pdf', to: "assetsusers#cetak_pdf"
        get 'cetak_excel', to: "assetsusers#cetak_excel"
    end
  end
  resources :assetssits
  # You can have the root of your site routed with "root"
  root to: 'dashboards#home'


  devise_for :users, path: '', path_names: { sign_in: 'login_page', sign_out: 'logout'}, controllers:{
    sessions: 'users/sessions'
  }
  resources :areas
  resources :roles
  resources :users

  # get ":category_id/", to: "dashboards#home"


  #sub_category
resources :dashboards do
  get "/insiden/", to: "dashboards#insiden_layanan"
  get "/request/", to: "dashboards#request_layanan"

end


  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/home"

  get "layoutsoptions/index"

  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/peity"
  get "graphs/sparkline"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/jqgrid"

  get "gallery/basic_gallery"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"


  mount RailsPerformance::Engine, at: 'rails/performance'


  # match '*path', via: :all, to: 'pages#not_found_error', constraints: lambda { |req|
  #   req.path.exclude? 'rails/active_storage'
  # }
  # get '/500', to: 'errors#internal_server_error'
  # get '/404', to: 'errors#not_found'
  # get '/422', to: 'errors#unprocessable_entity'
  
  # match '/500', via: :all, to: 'pages#internal_server_error'
  # match '/page_cannot_be_found', via: :all, to: 'pages#page_cannot_be_found'

end

app/models/message_template.rb
class MessageTemplate < ActiveRecord::Base
    belongs_to :category, foreign_key: 'kategori', primary_key: 'name'
  
    # scope :insiden, -> { 
    #   joins(:category).select('message_templates.*, categories.sub_category AS category_sub_category')
    #   .where("lower(jenis_layanan) = ? OR jenis_layanan = ''", jenis_layanan.downcase)
    #   .where("message_templates.sub_category IS NULL OR message_templates.sub_category = ''")
    #   .where("categories.sub_category != ''")
    #   .order(id: :asc) 
    # }
end

app/controllers/message_templates_controller.rb
class MessageTemplatesController < ApplicationController
  before_action :set_message_template, only: %i[ show edit update destroy ]

  # GET /message_templates or /message_templates.json
  def index
    @message_templates = MessageTemplate.all
  end

  # GET /message_templates/1 or /message_templates/1.json
  def show
  end

  # GET /message_templates/new
  def new
    @message_template = MessageTemplate.new
  end

  # GET /message_templates/1/edit
  def edit
  end

  # POST /message_templates or /message_templates.json
  def create
    @message_template = MessageTemplate.new(message_template_params)

    respond_to do |format|
      if @message_template.save
        format.html { redirect_to message_template_url(@message_template), notice: "Message template was successfully created." }
        format.json { render :show, status: :created, location: @message_template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message_template.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /message_templates/1 or /message_templates/1.json
  def update
    respond_to do |format|
      if @message_template.update(message_template_params)
        format.html { redirect_to message_template_url(@message_template), notice: "Message template was successfully updated." }
        format.json { render :show, status: :ok, location: @message_template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_templates/1 or /message_templates/1.json
  def destroy
    @message_template.destroy

    respond_to do |format|
      format.html { redirect_to message_templates_url, notice: "Message template was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message_template
      @message_template = MessageTemplate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_template_params
      params.require(:message_template).permit(:name, :template, :sub_category, :jenis_layanan, :kategori, :approvals)
    end
end

app/helpers/message_templates_helper.rb
module MessageTemplatesHelper
end

app/views/message_templates/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Form message_template</div>
  <div class="panel-body">
<%= form_for(@message_template, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @message_template.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@message_template.errors.count, "error") %> prohibited this message_template from being saved:</h4>

      <ul>
      <% @message_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Nama Template', class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", :required => true %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :template, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :template, class: "form-control", id: "keterangan", style: "resize: none; height: 10em;", :required => true %>
    </div>
  </div>
  


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
  </div>
</div>

<script>

  function setKategori(){ // https://stackoverflow.com/questions/1078118/how-do-i-iterate-over-a-json-structure
    var aru_id = $("#kategori").val();
    // console.log(aru_id);
    $.getJSON("/helper_json/" +aru_id+ "/getSubKategori",
      function ( callback ) {
      if (callback != "error"){
          // console.log(callback)
          for (var i = 0; i < callback.length; i++){
            var obj = callback[i];
              if (obj == null){
                $("#sub_category").empty();
                $("#jenis_layanan").empty();
              } else{
                $("#sub_category").empty();
                $("#sub_category").append('\
                  <option disabled selected>--Pilih Sub Kategori--</option>\
                ');
                var ukuran = obj['value'] ? JSON.parse(obj['value']) : "";
                for (var i = 0; i < ukuran.length; i++) { // https://stackoverflow.com/questions/9329446/for-each-over-an-array-in-javascript
                    var value = ukuran[i];
                    // ...use `element`...
                    $("#sub_category").append(new Option(value));
                    // console.log(value);
                }


         
                // $("#jenis_layanan").empty();
                // var tipe_layanan = obj['tipe_layanan']
                //     // ...use `element`...
                // $("#jenis_layanan").val(tipe_layanan);

                // var template = obj['template']
                //     // ...use `element`...
                // $("#keterangan").val(template);

                // $("#status_tiket").empty();
                // var status_tiket = obj['status_tiket']
                //     // ...use `element`...
                // $("#status_tiket").val(status_tiket);
              }
          }
      }
    });
  }
 jQuery(function () {
  var kategori = $('#kategori').val();
  var sub_category = $('#sub_category').val();
   
  if (kategori != "") {    
    $.getJSON("/helper_json/" + kategori + "/getSubKategori",
      function (callback) {
        if (callback != "error") {
          for (var i = 0; i < callback.length; i++) {
            var obj = callback[i];
            if (obj == null) {
              $("#sub_category").empty();
              $("#jenis_layanan").empty();
            } else {
              $("#sub_category").empty();
              var ukuran = obj['value'] ? JSON.parse(obj['value']) : "";
              for (var j = 0; j < ukuran.length; j++) { 
                var value = ukuran[j];
                var selected = value === sub_category ? 'selected="selected"' : '';
                $("#sub_category").append('\
                  <option value="' + value + '" ' + selected + '>' + value + '</option>\
                ');
              }

              $("#jenis_layanan").empty();
              var tipe_layanan = obj['tipe_layanan'];
              $("#jenis_layanan").val(tipe_layanan);

              $("#status_tiket").empty();
              var status_tiket = obj['status_tiket'];
              $("#status_tiket").val(status_tiket);
            }
          }
        }
      });
  }
});



</script>

app/views/message_templates/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form message_template</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= message_templates_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to message_templates_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
    <% end %>
    <%= link_to @message_template, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
    <% end %>
    <h1>Editing message_template</h1>
  </div>

  <%= render 'form' %>
</div>

app/views/message_templates/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form message_template</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= message_templates_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to new_message_template_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Message template
    <% end %>
    <!--    <h1>Listing </h1>-->
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover dataTables-example">
      <thead>
      <tr>
        <th>No</th>
        <th>Nama Template</th>
                  <th>Template</th>
                  <%# <th>Kategori</th>
                  <th>Sub category</th>
                  <th>Jenis layanan</th> %>
                <th>Aksi</th>
        <%# <th></th>
        <th></th> %>
      </tr>
      </thead>

      <tbody>
      <% @message_templates.each_with_index do |message_template, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= message_template.try(:name) %></td>
        <td><%= message_template.try(:template) %></td>
<%
=begin%>
        <td><%= message_template.try(:kategori) %></td>
        <td><%= message_template.try(:sub_category) %></td>
        <td><%= message_template.try(:jenis_layanan) %></td>
<%
=end%>
        <td>
            <%= link_to 'Show', message_template %>
            <%= link_to 'Edit', edit_message_template_path(message_template) %>
            <%= link_to 'Destroy', message_template, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/message_templates/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form message_template</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= message_templates_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <%= render 'form' %>
</div>

app/views/message_templates/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form message_template</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= message_templates_url %>">List</a>
      </li>
      <li class="active">
        <strong>Detail</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to message_templates_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
    <% end %>
    <%= link_to edit_message_template_path(@message_template), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
    <% end %>
<!--    <h1>Show </h1>-->
  </div>

  <dl class="dl-horizontal">
      <dt>Template:</dt>
      <dd><%= @message_template.template %></dd>

      <dt>Sub category:</dt>
      <dd><%= @message_template.sub_category %></dd>

      <dt>Jenis layanan:</dt>
      <dd><%= @message_template.jenis_layanan %></dd>

  </dl>
</div>