config/routes.rb
Myapp::Application.routes.draw do

  resources :feature_assignments
  resources :features
  get 'landing/set_role'

  mount ActionCable.server => '/cable'
  resources :ticket_approvals do
    member do
      post 'approvals', to: "ticket_approvals#approve"
      post 'reject', to: "ticket_approvals#reject"
      # post 'ticket_approvals/reject'
      # post 'ticket_approvals/approve'
    end
  end  
  resources :ticket_problems
  resources :message_templates
  resources :assetlisensis
  resources :assetssystems
  resources :changes do
    member do 
      delete "delete_file/:attachment_id", to: 'changes#delete_file'  
    end
  end
  resources :process_tickets do
    member do
      get "processTechnician", to: "process_tickets#processTechnician"
      get "processClosingAdmin", to: "process_tickets#processClosingAdmin"
      get "confirmWaiting", to: "process_tickets#confirmWaiting"
      get "createProblem", to: "process_tickets#createProblem"
      get "createPriority", to: "process_tickets#createPriority"
    end
  end
  post 'process_tickets/createFollowupTechnician'
  post 'process_tickets/followup'
  post 'process_tickets/createClosing'
  post 'process_tickets/createSatisfaction'
  post 'process_tickets/createSatisfactionEskalasi'
  post 'users/updateProfileForSelfService'
  resources :loss_events
  resources :positions
  # post '/update_session', to: 'helper_json#update_session_feature'
  post '/update_session_feature', to: 'helper_json#update_session_feature'


  resources :helper_json do
    collection do

      get "/getTemplateTiket", to: "helper_json#getTemplateTiket"
    end
    member do
      
      get 'destroy_chat', to: 'helper_json#destroy_chat', as: 'ticket_destroy_chat'

      get "getTemplatesByJenisLayanan", to: "helper_json#getTemplatesByJenisLayanan"
      get "getTemplatesBySubKategori", to: "helper_json#getTemplatesBySubKategori"

      get "getTemplatesByKategori/:kategori_id", to: "helper_json#getTemplatesByKategori"
      get "getTemplatesInAdminByKategori/:kategori_id", to: "helper_json#getTemplatesInAdminByKategori"
      

      get "getTemplates/:jenis_layanan", to: "helper_json#getTemplates"

      get "getSubKategori", to: "helper_json#getSubKategori"
      get "getSubKategori2", to: "helper_json#getSubKategori2"
      get "getPriority", to: "helper_json#getPriority"
      get "getStatusTeknisi", to: "helper_json#getStatusTeknisi"
      get "switchRole", to: "helper_json#switchRole"
      get "getTeknisi", to: "helper_json#getTeknisi"
      get "getPic", to: "helper_json#getPic"
      get "getStatus", to: "helper_json#getPic"
      get "getMerkPerangkat", to: "helper_json#getMerkPerangkat"
      get "getTipePerangkat", to: "helper_json#getTipePerangkat"
      get "getSubLayanan", to: "helper_json#getSubLayanan"
      get "getPerintilan", to: "helper_json#getPerintilan"
      get "getLayanan", to: "helper_json#getLayanan"
    end
  end
  resources :tickets do
    # get "notification", to: "tickets#read_ticket"


    collection do
      get 'cetak_pdf', to: "tickets#cetak_pdf"
      get 'cetak_excel', to: "tickets#cetak_excel"
      get 'detail_notif', to: "tickets#detail_notif"
      
    end
    member do
      get "superadminEdit", to: "tickets#superadminEdit"
      get "follow_up", to: "tickets#follow_up"
      get "answer", to: "tickets#answer"
      get "notification", to: "tickets#read_ticket"
      get 'chat_notif/:ticket_history', to: 'tickets#read_ticket_chat', as: 'chat_notif_ticket'      
      get "read_all_notifications/:ticket_history", to: "tickets#read_all_notifications", as: "read_all_notifications"
    end

  end
  resources :collection_assets
  resources :categories do
    member do 
      delete "delete_file/:attachment_id", to: 'categories#delete_file'   
    end
  end
  resources :service_types
  resources :assetsdigitals do
    collection do 
      post :import
    end
  end

  resources :assetsusers do
    member do 
      delete "delete_file/:attachment_id", to: 'assetsusers#delete_file'   
    end
    collection do
      post :import
        get 'cetak_pdf', to: "assetsusers#cetak_pdf"
        get 'cetak_excel', to: "assetsusers#cetak_excel"
    end
  end
  resources :assetssits
  # You can have the root of your site routed with "root"
  root to: 'dashboards#home'


  devise_for :users, path: '', path_names: { sign_in: 'login_page', sign_out: 'logout'}, controllers:{
    sessions: 'users/sessions'
  }
  resources :areas
  resources :roles
  resources :users

  # get ":category_id/", to: "dashboards#home"


  #sub_category
resources :dashboards do
  get "/insiden/", to: "dashboards#insiden_layanan"
  get "/request/", to: "dashboards#request_layanan"

end


  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/home"

  get "layoutsoptions/index"

  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/peity"
  get "graphs/sparkline"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/jqgrid"

  get "gallery/basic_gallery"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"


  mount RailsPerformance::Engine, at: 'rails/performance'


  # match '*path', via: :all, to: 'pages#not_found_error', constraints: lambda { |req|
  #   req.path.exclude? 'rails/active_storage'
  # }
  # get '/500', to: 'errors#internal_server_error'
  # get '/404', to: 'errors#not_found'
  # get '/422', to: 'errors#unprocessable_entity'
  
  # match '/500', via: :all, to: 'pages#internal_server_error'
  # match '/page_cannot_be_found', via: :all, to: 'pages#page_cannot_be_found'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :service_type
  has_many :message_templates, foreign_key: 'kategori', primary_key: 'name'
  has_one_attached  :lampiran_icon
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  load_and_authorize_resource
  respond_to :html, :json
  
  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    @sub_category = 
    if (@category.sub_category.nil? or @category.sub_category.empty?)
      []
    else
      @category.sub_category[0, 1] == "[" ? JSON::parse(@category.sub_category) : []
    end

    if @sub_category.empty?
      @jenis_layanan = []
      @templates_id = []
      @approved = []
      else
        @jenis_layanan = Array.new(@sub_category.length, [])
        @templates_id = Array.new(@sub_category.length, [])
        @approved = Array.new(@sub_category.length, [])

      @jenis_layanan = @jenis_layanan.map.with_index do |jenis_layanan, i|
        if (@category.jenis_layanan.nil? or @category.jenis_layanan.empty?)
        []
        else
          @category.jenis_layanan[0, 1] == "[" ? JSON::parse(@category.jenis_layanan)[i] : []
        end
      end

      @templates_id = @templates_id.map.with_index do |template, i|
        if (@category.templates_id.nil? or @category.templates_id.empty?)
        []
        else
        @category.templates_id[0, 1] == "[" ? JSON::parse(@category.templates_id)[i] : []
        end
      end

      @approved = @approved.map.with_index do |approved, i|
        if (@category.approved.nil? or @category.approved.empty?)
        []
        else
          @category.approved[0, 1] == "[" ? JSON::parse(@category.approved)[i] : []
        end
      end
    end            

  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    unless params[:category][:sub_category].nil?
      @array = []
      @array = params[:category][:sub_category]
      @array_jenis_layanan = []
      @array_jenis_layanan = params[:category][:jenis_layanan]
      @array_approved = []
      @array_approved = params[:category][:approved]
      @array_template_id = []
      @array_template_id = params[:category][:templates_id]
      @category.sub_category = @array
      @category.jenis_layanan = @array_jenis_layanan
      @category.approved = @array_approved
      @category.templates_id = @array_template_id
    end
    respond_to do |format|
      if @category.save
        # format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
      # s
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        unless params[:category][:sub_category].nil?
          @array = []
          @array = params[:category][:sub_category]
          @array_jenis_layanan = []
          @array_jenis_layanan = params[:category][:jenis_layanan]
          @array_template_pesan = []
          @array_template_pesan = params[:category][:templates_id]
          @array_approved = []
          @array_approved = params[:category][:approved]
          @category.update(
            sub_category: @array,
            jenis_layanan: @array_jenis_layanan,
            templates_id: @array_template_pesan,
            approved: @array_approved
          )
        end
        
        # format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_file
    @attachment = ActiveStorage::Attachment.find(params[:attachment_id])
    @attachment.purge # or use purge_later
    redirect_back(fallback_location: request.referer)
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :sub_layanan, :sub_category, :service_type_id, :template, :status_template_tiket, :pic, :jenis_layanan, :jenis_layanan_kategori, :deskripsi_kategori, :approved,:lampiran_icon)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form category</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= categories_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
    <% end %>
    <%= link_to @category, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
    <% end %>
    <h1>Editing category</h1>
  </div>

  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form category</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= categories_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to new_category_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Category
    <% end %>
    <!--    <h1>Listing </h1>-->
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover dataTables-example">
      <thead>
      <tr>
        <th>No</th>
                  <th>Name</th>
                  <th>Sub category</th>
                  <%# <th>Service type</th> %>
                  <%# <th>PIC</th> %>
                <th>Aksi</th>
        <%# <th></th>
        <th></th> %>
      </tr>
      </thead>

      <tbody>
      <% @categories.each_with_index do |category, index| %>
      <tr>
        <td><%= index+1 %></td>
                  <td><%= category.name %></td>
                  <td><%= category.sub_category.gsub('"','').gsub('[','').gsub(']','') %></td>
                  <%# <td><%= category.service_type.nama %>
<%
=begin%>                  
                  <td><%= category.pic %></td>
<%
=end%>
        <td>
            <%= link_to 'Show', category %>
            <%= link_to 'Edit', edit_category_path(category) %>
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form category</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>
        <a href="<%= categories_url %>">List</a>
      </li>
      <li class="active">
        <strong>Form</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Form category</h2>
    <ol class="breadcrumb">
      <li>
        <a href="">Home</a>
      </li>
      <li>   
        <a href="<%= categories_url %>">List</a>
      </li>
      <li class="active">
        <strong>Detail</strong>
      </li>
    </ol>
  </div>
</div>
<br>
<div id="content">
  <div class="page-header">
    <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
    <% end %>
    <%= link_to edit_category_path(@category), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
    <% end %>
<!--    <h1>Show </h1>-->
  </div>
<div class="panel-heading">Detail Kategori</div>
  <div class="panel-body">
  <dl class="dl-horizontal">
      <dt>PIC :</dt>
      <dd><%= @category.try(:pic) %></dd>

<%
=begin%>
      <dt>Sub category:</dt>
      <dd><%= @category.sub_category %></dd>

      <dt>Sub Layanan</dt>
      <dd><%= @category.sub_layanan %></dd>

      <dt>Kendala:</dt>
      <dd><%= @category.kendala %></dd>

      <dt>Service type:</dt>
      <dd><%= @category.template %></dd>
<%
=end%>
  </dl>
</div>
</div>
</div>